# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HkYwuJK9RAic4HzLq3A-HMXOrzGYx6A
"""

import cv2
import matplotlib.pyplot as plt

image1 = cv2.imread("rasm1.jpg")
image2 = cv2.imread("rasm2.jpg")
image3 = cv2.imread("rasm3.jpg")


gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
gray3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

axes[0].imshow(gray1, cmap='gray')
axes[0].set_title("Rasm 1 - Grayscale")
axes[0].axis("off")

axes[1].imshow(gray2, cmap='gray')
axes[1].set_title("Rasm 2 - Grayscale")
axes[1].axis("off")

axes[2].imshow(gray3, cmap='gray')
axes[2].set_title("Rasm 3 - Grayscale")
axes[2].axis("off")

plt.show()